apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: manager
    app.kubernetes.io/name: ebpfdump-operator
    app.kubernetes.io/managed-by: kustomize
  name: system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: manager
  namespace: system
  labels:
    control-plane: manager
    app.kubernetes.io/name: ebpfdump-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: manager
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      securityContext:
        runAsNonRoot: true
      containers:
      - command:
        - /manager
        args:
          - --ebpfdump-health-probe-bind-address=:8081
        image: ebpfdump-operator:latest
        name: ebpfdump-operator
        securityContext:
          runAsNonRoot: false
          privileged: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: manager
      terminationGracePeriodSeconds: 10
