apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: default
  labels:
    app.kubernetes.io/name: nginx-pod
    security-level: high 
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
