apiVersion: v1
kind: Pod
metadata:
  name: apache
  namespace: default
  labels:
    app: apache
spec:
  containers:
    - name: apache
      image: ubuntu/apache2
      ports:
        - containerPort: 81
